/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "\tGain from Bat:": "\t从蝙蝠获得：",
    "\tGain from Bingo:": "\t从宾果游戏中获得：",
    "\tGain from Crit:": "\t暴击增益：",
    "\tGain from Garb:": "\t从 Garb 获得：",
    "\tGain from Ice:": "\t从冰获得：",
    "\tGain from Magic:": "\t从魔法中获得：",
    "\tGain from MELT:": "\t从 MELT 中获得：",
    "\tGain from Ship:": "\t从船上获得：",
    "\tGain from Shoes:": "\t从鞋子中获得：",
    "\tGain from Spade:": "\t从黑桃获得：",
    "\tGain from YAHTZEE:": "\t从 YAHTZEE 获得：",
    "\tMoney Spent on Bat:": "\t花在蝙蝠上的钱：",
    "\tMoney Spent on Bingo:": "\t花在宾果游戏上的钱：",
    "\tMoney Spent on Garbage:": "\t在垃圾上花费的金钱：",
    "\tMoney Spent on Ice Cubes:": "\t花在冰块上的钱：",
    "\tMoney Spent on Magic:": "\t花在魔法上的钱：",
    "\tMoney Spent on Shoes:": "\t花在鞋子上的钱：",
    "\tMoney Spent on Spaceship:": "\t在宇宙飞船上花费的金钱：",
    "\tMoney Spent on Spade:": "\t花在黑桃上的钱：",
    "\tTotal Gain:": "\t总增益：",
    "\tTotal Money:": "\t总金额：",
    "\tTotal Ticks:": "\t总Tick：",
    "'Fresh' Meat": "'鲜肉",
    "% full. It currently increases all of the ♠ you earn by": "％ 满的。它目前会增加您赚取的所有♠",
    "% full. It currently increases all of the $ you earn by": "％ 满的。它目前会增加您赚取的所有美元",
    "% full. You have sacrificed a total of $": "％ 满的。您总共牺牲了 $",
    "% increased production for 10 ticks. (Based on amount of Spaceships owned)\n": "% 增加了 10 刻的产量。 （基于拥有的宇宙飞船数量）\n",
    "% more gain every tick. This bonus is reduced by 70% when a Batsplosion occurs\n": "每Tick增加 % 增益。发生蝙蝠爆炸时，此加成会降低 70%\n",
    "%! You have sacrificed a total of": "%！你总共牺牲了",
    "☺ to unlock the next building. Fully unlocking a buildings potential gives that building a 10% chance to produce ♠\n": "☺ 解锁下一座建筑。完全解锁建筑物的潜力使该建筑物有 10% 的几率生产 ♠\n",
    "☺. Ice Cubes have a 10% chance to reform when melted. Each give $": "☺。冰块融化时有 10% 的几率重新形成。每个给$",
    "♠s for this cause\n": "♠s 因为这个原因\n",
    "24 Carrot Bats": "24 胡萝卜蝙蝠",
    "3.14 Trillion": "3.14 万亿",
    "398.54 Trillion": "398.54 万亿",
    "A card game for parties and old people homes. Every": "适合聚会和老人院的纸牌游戏。每一个",
    "A peacefully sleeping Giant. It is said that this giant only awakens once every 50 ticks. If you listen closely you can hear faint whispers echoing \"wake me up (CAN'T WAKE UP)\". When awake giants can produce ∞. Each gives $": "一个沉睡的巨人。据说这个巨人每50刻才醒来一次。如果你仔细听，你会听到微弱的耳语回荡着“叫醒我（不能醒来）”。当醒着的巨人可以产生∞。每个给$",
    "A single red paper clip. The potential for this baby is infinite! The more money that has been spent on other buildings increase the value of this one! Better get trading. Gives ∞! Each gives $": "一个红色回形针。这个宝贝的潜力是无限的！花在其他建筑物上的钱越多，这栋建筑物的价值就越高！更好地进行交易。给∞！每个给$",
    "a tick and you gain a total of $": "一个勾号，您总共获得 $",
    "a tick for a magical total of $": "一个勾号，总价值为 $",
    "a tick for a total of $": "一个勾号，总计 $",
    "a tick when awake for a total of $": "醒时打勾，总共 $",
    "a tick. Your next Spaceship gives $": "一个勾号。你的下一艘宇宙飞船给了 $",
    "A tool typically used for digging up money. Each Spade has a chance of letting you dig a mile to earn bonus Shoe production for a tick! Each dig has a reduced chance to dig again! Each give $": "一种通常用于挖钱的工具。每个黑桃都有几率让您挖一英里以赚取额外的鞋子产量！每次挖掘都有减少再次挖掘的几率！每个给$",
    "Allows you to unlock the hidden potential of Bingos. Doing so leads to easier Bingos and stronger Bingo Bucks\n": "让您解锁宾果游戏的隐藏潜力。这样做会导致更轻松的宾果游戏和更强大的宾果游戏雄鹿\n",
    "Allows you to unlock the hidden potential of Garbage. Doing so leads to more powerful bonuses based on the number of Garbage\n": "让您释放垃圾的隐藏潜力。这样做会根据垃圾数量获得更强大的奖励\n",
    "Allows you to unlock the hidden potential of Gold Bat 9000. Doing so leads to reduced Batsplosions and cumulative Gold Bat 9000 gains\n": "允许您解锁 金蝙蝠 9000 的隐藏潜力。这样做会减少 蝙蝠球 和累积 金蝙蝠 9000 收益\n",
    "Allows you to unlock the hidden potential of Ice Cubes. Doing so leads to strong faster better and permanent Ice Cubes\n": "让您解锁冰块的隐藏潜力。这样做会导致更强更快更好和永久的冰块\n",
    "Allows you to unlock the hidden potential of Magic. Doing so leads to improved φ generation and time altering magic\n": "让您释放魔法的隐藏潜力。这样做可以改进 φ 生成和时间改变魔法\n",
    "Allows you to unlock the hidden potential of Shoes. Doing so leads to a drastic increase to shoe production and the ability to run through time\n": "让您释放鞋子的隐藏潜力。这样做会大大增加鞋子的产量和穿越时间的能力\n",
    "Allows you to unlock the hidden potential of Spaceships. Doing so leads to vastly increased Spaceship production and reduced costs\n": "允许您解锁宇宙飞船的隐藏潜力。这样做会大大增加 宇宙飞船 的产量并降低成本\n",
    "Allows you to unlock the hidden potential of Spades. Doing so leads to Dig multiplier bonuses and stronger Digs\n": "让您释放黑桃的隐藏潜力。这样做会带来挖掘乘数奖励和更强的挖掘\n",
    "Alter Time": "改变时间",
    "Average $ per second:": "平均 $ 每秒：",
    "Awake:": "苏醒：",
    "Bagger 288": "巴格 288",
    "Bat Chains": "蝙蝠链",
    "Baterest Value:": "最低值：",
    "Batsplode Chance:": "爆破几率：",
    "Batsplode Immunity:": "蝙蝠爆发免疫：",
    "Batsplosions are 10% less effective\n": "爆破效果降低 10%\n",
    "Batsplosions can no longer happen more than twice in a row\n": "蝙蝠爆炸不能再连续发生两次以上\n",
    "Batsplosions reduce the remaining time on Ice Cubes by 1 ticks\n": "爆破使冰块的剩余时间减少 1 刻\n",
    "Better Equipment": "更好的设备",
    "Bigger Gains": "更大的收益",
    "Bingo": "宾果",
    "BINGO ball will be called out. The more bingo cards you have the better the payout! Each give $": "宾果 球将被叫出。您拥有的宾果卡越多，支出就越好！每个给$",
    "BINGO Balls": "宾果球",
    "Bingo Bucks:": "宾果雄鹿：",
    "Bingo cards now start with a free space in the middle\n": "宾果卡现在从中间的空闲空间开始\n",
    "Bingo Chain:": "宾果链：",
    "BINGO²": "宾果²",
    "BINGOs have a 15% chance to reduce the remaining time on Ice Cubes by 1\n": "宾果 有 15% 的几率将冰块的剩余时间减少 1\n",
    "Bladed Shoes": "刃鞋",
    "Blast Wave": "冲击波",
    "Bonus Gain:": "奖金收益：",
    "Bribe the Caller": "贿赂来电者",
    "Brighter Lights": "更亮的灯",
    "Brittle Ice": "脆冰",
    "Buy": "购买",
    "Chain Reaction": "连锁反应",
    "Challenger": "挑战者",
    "Chilled Time": "冷藏时间",
    "Cloned Spades": "克隆黑桃",
    "Cold Bat 9000": "冷蝙蝠 9000",
    "Colder Cubes": "更冷的立方体",
    "Columbia": "哥伦比亚",
    "Compounding Baterest": "复合电池",
    "Conjure Money": "变钱",
    "Conjure Money:": "召唤金钱：",
    "Consume all of your Moana to summon a random Dream": "消耗你所有的莫阿娜来召唤一个随机的梦境",
    "Contained Batsplosions": "包含的蝙蝠爆炸",
    "Convert all of your $, φ, ☺, and ♠ into §. Sacrificing now will give": "将你所有的 $、φ、☺ 和 ♠ 转换为 §。现在牺牲会给",
    "Cost: $": "费用：$",
    "Current Gain:": "当前增益：",
    "Currently owned:": "目前拥有：",
    "Diamond in the Rough": "粗糙的钻石",
    "Dig Chance:": "挖掘几率：",
    "Dig Dug": "挖挖",
    "Dig Multiplier:": "挖掘乘数：",
    "Dig Value:": "挖掘价值：",
    "Digging Frenzy": "疯狂挖掘",
    "Digs have a 20% chance to increase Shoe production by 70000% for the 10 ticks. This bonus does not count towards dig bonuses\n": "挖掘 10 次有 20% 的几率使鞋子的产量增加 70000%。此奖金不计入挖掘奖金\n",
    "Digs have a 5% chance to reduce the remaining ticks on Ice Cubes by 1\n": "挖掘有 5% 的几率使冰块上剩余的Tick减少 1\n",
    "Digs now use 150% of Shoe production \n": "挖掘现在使用 150% 的鞋子产量\n",
    "Dirty Digs": "肮脏的挖掘",
    "Dump all of your ♠ into your Mana pool. Your Mana is channelled to increase all of the $ you earn.\n": "将你所有的 ♠ 倾倒到你的法力池中。你的法力值被引导来增加你赚取的所有美元。\n",
    "Dump all of your ♠ into your Manna pool. Your Manna is channelled to increase all of the ♠ you earn.\n": "将你所有的 ♠ 倾倒到你的甘露池中。你的 Manna 被引导来增加你获得的所有 ♠。\n",
    "Dump all of your $ into your Moana pool. Your Moana is channelled for a mysterious effect that is not yet known.\n": "把你所有的美元都扔到你的莫阿纳池里。你的莫阿娜被引导了一个未知的神秘效果。\n",
    "Dumpster Diving": "垃圾箱潜水",
    "Duplicate Trick": "重复技巧",
    "Each BINGO within the same tick increase the Bingo Bucks reward by 5% \n": "同一Tick中的每个 宾果 将 宾果雄鹿 奖励增加 5% \n",
    "each tick when awake. Buying one now has a worth of": "清醒时的每一个Tick。现在买一个价值",
    "each tick. Buying one now has a Gain/Cost Ratio of": "每个Tick。现在购买一个的收益/成本比为",
    "each tick. Buying one now has a worth of": "每个Tick。现在买一个价值",
    "each tick. Magically buying one now has a magical worth of": "每个Tick。神奇地买一个现在有一个神奇的价值",
    "Efficient Engineering": "高效工程",
    "Elevator Shoes": "电梯鞋",
    "Engage Thrusters": "接合推进器",
    "Every 10 Spaceships gives a free Spaceship\n": "每 10 艘宇宙飞船免费赠送一艘宇宙飞船\n",
    "Every 25 shoes give 1% crit\n": "每 25 只鞋子给予 1% 暴击\n",
    "Every 40 ticks Spaceships give": "宇宙飞船每 40 个Tick",
    "Every BINGO has a 15% chance to grant an extra BINGO\n": "每个 宾果 都有 15% 的几率额外授予一个额外的 宾果\n",
    "Exotic Goods": "异国商品",
    "Exploding Spades": "爆炸的黑桃",
    "extra ♠\n": "额外的♠\n",
    "Extra Balls": "额外的球",
    "Faster Feet": "更快的脚",
    "Faster Illusions": "更快的幻觉",
    "Feedback Loop": "反馈回路",
    "Fiery Spades": "火热的黑桃",
    "for this cause. You need $": "为此。你需要 $",
    "Foreign Production": "国外生产",
    "Free Rabbits": "免费兔子",
    "Free Water": "免费水",
    "Frozen Forever": "永远冻结",
    "Gaining 10 φ in a single tick has a 30% chance to reduce tick rate by .7 seconds for 20 ticks\n": "在单个刻获得 10 φ 有 30% 的几率将刻速率降低 0.7 秒，持续 20 个刻\n",
    "Gaining a φ has a 10% chance to reduce the remaining ticks on Ice Cubes by 1\n": "获得 φ 有 10% 的几率将冰块上的剩余Tick减少 1\n",
    "Game has been loaded": "游戏已加载",
    "Game has been saved": "游戏已保存",
    "Garbage": "垃圾",
    "Garbage Bag Sack Races": "垃圾袋赛跑",
    "Garbage can now always give ♠ and can give": "垃圾现在总是可以给 ♠ 并且可以给",
    "Getting 5 consecutive digs will triple dig multiplier for the next dig\n": "获得 5 次连续挖掘将使下一次挖掘的挖掘乘数增加三倍\n",
    "Getting Old Fast": "快速变老",
    "Gold Bat 9000": "金蝙蝠9000",
    "Gold Bat 9000s have": "金蝙蝠 9000s 有",
    "Gold Bat 9001": "金蝙蝠9001",
    "Gold Bat Fail Safe": "金蝙蝠故障保险",
    "GOLD STRUCK": "黄金打击",
    "Handicapped": "残疾人",
    "Head Start": "抢先一步",
    "Heating up the Competition": "让比赛升温",
    "Hidden Value": "隐藏的价值",
    "Ice Cubes": "冰块",
    "Ice Cubes always reform when they melt\n": "冰块融化时总是会重组\n",
    "Ice Cubes give an extra ☺ when they melt\n": "冰块融化时会额外提供 ☺\n",
    "Ice Cubes have a 25% chance to reduce their remaining tick duration by 1 during Lift Off\n": "在升空期间，冰块有 25% 的几率将其剩余的Tick持续时间减少 1\n",
    "Ice Cubes have a 3% chance to instantly melt when below 50 ticks remaining\n": "冰块剩余 50 刻以下时有 3% 的几率立即融化\n",
    "Ice Cubes have a 50% chance to reform when they melt\n": "冰块融化时有 50% 的几率重整\n",
    "Increase dig multiplier by 10% for each consecutive dig\n": "每次连续挖掘将挖掘乘数提高 10%\n",
    "Increases chance to dig by 0.5% \n": "挖掘机率增加 0.5% \n",
    "Increases dig chance by 2% \n": "挖掘几率提高 2% \n",
    "Increases Rocket Fuel discount by 10%\n": "火箭燃料折扣增加 10%\n",
    "Increases Shoe Gain by 100% per Shoe owned. This increase does not count towards dig bonuses\n": "每拥有一只鞋子，鞋子增益增加 100%。此增加不计入挖掘奖金\n",
    "Increases the amount of money you gain from ice melting by about 5%\n": "使你从融冰中获得的金钱增加约 5%\n",
    "Increases the base gain of Garbage by 100%\n": "将垃圾的基础增益提高 100%\n",
    "Increases the base gain of Gold Bat 9000s by 75%\n": "将 Gold Bat 9000 的基础增益提高 75%\n",
    "Increases the base gain of Ice Cubes by 10%\n": "增加冰块的基础增益 10%\n",
    "Increases the base gain of Magic by 40%\n": "魔法基础增益提高 40%\n",
    "Increases the base income of Bingos by 3\n": "将宾果游戏的基本收入提高 3\n",
    "Increases the base income of Shoes by 1 \n": "鞋子的基础收入增加 1 \n",
    "Increases the base income of Spaceships by 25\n": "增加宇宙飞船的基础收入 25\n",
    "Increases the base income of Spades by 8\n": "黑桃的基础收入增加 8\n",
    "Increases the bonus gain of Spaceships by 1%\n": "增加宇宙飞船的额外增益 1%\n",
    "Increases the bonus of Digging Frenzy by 5%\n": "疯狂挖掘的加成提高 5%\n",
    "Increases the bonus of Rotten Fruit by 5%\n": "腐烂果实加成提高5%\n",
    "Increases the chance for consecutive digs by 7%\n": "连续挖掘的几率提高 7%\n",
    "Increases the Chance for Garbage to give ♠ by 10%\n": "将垃圾给予 ♠ 的几率提高 10%\n",
    "Increases the chance to gain φ by 15%\n": "获得 φ 的几率增加 15%\n",
    "Increases the Ice Cube Batsplosion reduction by 10%\n": "增加冰块蝙蝠爆炸减少 10%\n",
    "Increases the number of BINGO balls called out by 1\n": "将召唤出的 宾果球 的数量增加 1\n",
    "Increases the scaling on the Bingo Bucks reward by 6%\n": "将 宾果雄鹿 奖励的比例提高 6%\n",
    "Increases your dig multiplier by 0.1 for each non-Spade building you own\n": "对于您拥有的每个非黑桃建筑，您的挖掘乘数增加 0.1\n",
    "Is Another Man's Treasure": "是另一个男人的宝藏",
    "Landfill": "垃圾填埋场",
    "Lift Off": "起飞",
    "Lift Off T-minus:": "升空 T 减：",
    "Lighter Material": "打火机材质",
    "Liquid Trash": "液体垃圾",
    "Magic": "魔法",
    "Magic magically gives you magic money with a magical chance of producing φ. Magic! Each magically give $": "魔术神奇地给你神奇的钱，有一个神奇的几率产生 φ。魔法！每个神奇地给$",
    "Melt Value:": "熔体值：",
    "Monies": "钱",
    "more to fill it up\n": "更多以填补它\n",
    "Multiples of 3 Garbage cause every 3 ticks to perform an extra tick\n": "3 垃圾 的倍数导致每 3 个Tick执行一次额外Tick\n",
    "Multiples of 4 Garbage increases all $ earned by 5%\n": "4 的倍数垃圾将所有收入增加 5%\n",
    "Multiples of 5 Garbage Produce 7x the current gain of garbage\n": "5 的倍数垃圾产生 7 倍的当前垃圾增益\n",
    "Multiplier Duration:": "乘数持续时间：",
    "Multistep": "多重步骤",
    "Multistep:": "多重步骤：",
    "No Breaks": "没有休息",
    "One Man's Trash": "一个男人的垃圾",
    "OVERDRIVE:": "过载：",
    "Pie": "馅饼",
    "Plastic Rabbits": "塑料兔",
    "Pristine Water": "纯净水",
    "Pyrokinesis": "发火",
    "Recycling": "回收",
    "Red Paper Clip": "红色回形针",
    "Reduces the base cost of Garbage by 20%\n": "将垃圾的基本成本降低 20%\n",
    "Reduces the base cost of Magic by 20%\n": "将魔法的基础消耗降低 20%\n",
    "Reduces the base cost of Spaceships by 5%\n": "将宇宙飞船的基本成本降低 5%\n",
    "Reduces the base cost of Spades by 5% \n": "将黑桃的基本成本降低 5% \n",
    "Reduces the Batsplode chance by 10%\n": "将蝙蝠爆裂几率降低 10%\n",
    "Reduces the cost multiplier for Bingos by 0.15%\n": "将 Bingo 的成本乘数降低 0.15%\n",
    "Reduces the cost multiplier for Spaceships by 0.5%\n": "将宇宙飞船的成本乘数降低 0.5%\n",
    "Reduces the cost multiplier of Garbage by 10%\n": "将垃圾的成本乘数降低 10%\n",
    "Reduces the cost multiplier of Gold Bat 9000s by 10%\n": "将 Gold Bat 9000 的成本乘数降低 10%\n",
    "Reduces the cost multiplier of Ice Cubes by 10%\n": "将冰块的成本乘数降低 10%\n",
    "Reduces the cost multiplier of Magic by 0.2%\n": "将魔法的成本乘数降低 0.2%\n",
    "Reduces the cost multiplier of Shoes by 0.2% \n": "将鞋子的成本乘数降低 0.2% \n",
    "Reduces the cost multiplier of Spades by 0.2%\n": "将黑桃的成本乘数降低 0.2%\n",
    "Reduces the Critical Batsplode chance by 20%\n": "将暴击蝙蝠爆裂几率降低 20%\n",
    "Reduces the increasing Batsplode chance by 10%\n": "将增加的蝙蝠爆裂几率降低 10%\n",
    "Reduces the number of ticks for Ice Cubes to melt by 10\n": "将冰块融化的Tick减少 10\n",
    "Reduces the number of ticks for Ice Cubes to melt by 15\n": "将冰块融化的Tick减少 15\n",
    "Reduces the number of ticks for Ice Cubes to melt by 15 \n": "将冰块融化的Tick减少 15 \n",
    "Reduces the number of ticks for Ice Cubes to melt by 20\n": "将冰块融化的Tick减少 20\n",
    "Reduces the number of ticks needed to call out a BINGO ball by 10\n": "将调出 BINGO 球所需的Tick数减少 10\n",
    "Reduces the time between ticks by .02 seconds\n": "将Tick之间的时间缩短 0.02 秒\n",
    "Reduces the time between ticks by .03 seconds\n": "将Tick之间的时间缩短 0.03 秒\n",
    "Reduces the time between ticks by .05 seconds\n": "将Tick之间的时间缩短 0.05 秒\n",
    "Reset": "重置",
    "Reverse Melting": "逆熔",
    "Rocket Discount:": "火箭折扣：",
    "Rocket Fleet": "火箭舰队",
    "Rocket Fuel Leak": "火箭燃料泄漏",
    "Rotten Fruit": "烂果",
    "Run Chance:": "运行几率：",
    "RUN!": "跑！",
    "Running Friction": "运行摩擦",
    "Sacrifice all of your ∞ to gain x4 $, φ, ☺, and ♠. This effect lasts for": "牺牲所有 ∞ 来获得 x4 $、φ、☺ 和 ♠。这种效果持续",
    "Scrap Metal": "废金属",
    "Senior Discount": "高级折扣",
    "Sharp Digger": "锋利的挖掘机",
    "Shatter": "粉碎",
    "Shoes": "鞋",
    "Silver Bat 100": "银蝙蝠 100",
    "Sleeping Giant": "沉睡的巨人",
    "Snow Day": "下雪天",
    "Spaceship": "飞船",
    "Spaceships recycle rocket fuel over time. Rocket fuel is used to negotiate discounts on Spaceship purchases (up to 20% off)\n": "随着时间的推移，宇宙飞船会回收火箭燃料。火箭燃料用于协商购买 Spaceship 的折扣（最高 20% 折扣）\n",
    "Spade": "黑桃",
    "Special Snowflakes": "特殊雪花",
    "Stab the ground": "捅地",
    "Stinky smelly garbage. Different amounts of garbage produce different effects. When at an odd number of garbage they have a chance to give ♠. When at an even number, Time Warp is active and tick rate is greatly increased. Each gives $": "臭臭的垃圾。不同数量的垃圾产生不同的效果。当垃圾数量为奇数时，他们有几率给出♠。当为偶数时，时间扭曲处于活动状态，并且Tick率大大增加。每个给$",
    "Stronger Bats": "更强的蝙蝠",
    "Thawing": "解冻",
    "The Gold Bat 9000© is the 10th world wonder. Reaching insane speeds this baby out paces the Spookydook! However it's prone to failure but Ice Cubes help reduce the chance that it'll fail! Each gives $": "金蝙蝠 9000© 是第十个世界奇迹。达到疯狂的速度让这个婴儿快步 Spookydook！但是它很容易失败，但冰块有助于减少失败的几率！每个给$",
    "The once forgotten Pi(e). The sweet aroma fills you with money and reminds you of a better place. The smell has a 5% chance to condense into a physical form granting you ∞. Each gives $": "曾经被遗忘的 Pi(e)。甜美的香气让你充满金钱，让你想起一个更好的地方。气味有 5% 的几率凝结成物理形态，使你获得 ∞。每个给$",
    "The tick speed bonus from Time Warp is increased by 10%\n": "时间扭曲的Tick速度加成提高 10%\n",
    "The Weight of Many": "许多人的重量",
    "ticks": "Tick",
    "Ticks left to sleep:": "Tick剩余到睡觉：",
    "ticks. (Increased by more ∞)": "蜱。 （增加更多∞）",
    "ticks. When a cube melts it produces bonus money and": "蜱。当一个立方体融化时，它会产生奖金和",
    "Tie the Knot": "打结",
    "Time between ticks is reduced by .1 seconds \n": "T'i'c'k之间的时间减少了 0.1 秒 \n",
    "Time between ticks is reduced by 0.01 seconds \n": "Tick之间的时间减少了 0.01 秒 \n",
    "Time between ticks is reduced by 0.05 seconds \n": "Tick之间的时间减少了 0.05 秒 \n",
    "Time Till Next Melt:": "下一次融化的时间：",
    "Time's my name. Speed's my game": "时间是我的名字。速度是我的游戏",
    "Timewarp Remaining:": "剩余时间扭曲：",
    "Trade Duration:": "交易时间：",
    "Trading:": "贸易：",
    "Turn in your ☺ to unlock ONE buildings hidden potential! It currently costs": "交出你的 ☺ 来解锁 ONE 建筑物的隐藏潜力！目前成本",
    "Unstable Elements": "不稳定元素",
    "Up the Ante": "提高赌注",
    "VROOOOOOOOM. Spaceships bring in a lot of money but are really expensive. Each spaceship you own makes the next one exponentially better. Your current Spaceship gives $": "呜呜呜。宇宙飞船带来了很多钱，但真的很贵。你拥有的每艘宇宙飞船都会使下一艘飞船变得更好。你目前的宇宙飞船给了 $",
    "Warp Speed": "神速",
    "Wasting Time": "浪费时间",
    "Water frozen by magic and enchanted to give you money. Ice Cubes melt over": "水被魔法冻结并附魔给你钱。冰块融化",
    "When an Ice Cube Melts Gold Bat 9000s cannot fail for 4 ticks\n": "当冰块融化金蝙蝠时，9000s 不会失败 4 刻\n",
    "When an Ice Cube melts you gain up to": "当冰块融化时，您最多可以获得",
    "when you gain a φ\n": "当你获得一个 φ\n",
    "When you gain a φ you have a 25% chance to gain another\n": "当你获得一个 φ 时，你有 25% 的几率获得另一个\n",
    "You gain $": "您获得 $",
    "YOU WIN!": "你赢了！",
    "Your Mana pool is": "你的法力池是",
    "Your Manna pool is": "你的甘露池是",
    "Your Moana pool is": "您的 Moana 游泳池是",
    "Your Shoes have a 5% chance to run giving 5 ticks insead of 1 \n": "你的鞋子有 5% 的几率运行 5 个Tick而不是 1 \n",
    "Your Shoes now have an additional 5% chance to run \n": "你的鞋子现在有额外 5% 的几率奔跑\n",
    "Your standard pair of shoes. Each pair lets you walk a mile in someone else's shoe! Each give $": "你的标准鞋。每双都可以让您穿着别人的鞋子走一英里！每个给$",
    "φ for next upgrade:": "φ 下一次升级：",
    "Max": "最大",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "§": "§",
    "%": "%",
    "∞": "∞",
    "$": "$",
    "☺": "☺",
    "♠": "♠",
    "φ": "φ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) Quadrillion$/,
    /^([\d\.]+) Trillion$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);